### ISSUE TITLE
Unable to build on WSL Debian

### ISSUE THREAD

**Issue by jsmolka** [mgba-emu/suite#12]
I am using the Debian version of WSL and am unable to build the test suite. I get the following error:

```
grit -ff /home/jsmolka/suite/gfx/videotest.grit -fts -ovideotest
videotest.s
arm-none-eabi-gcc: error: videotest.s: No such file or directory
arm-none-eabi-gcc: fatal error: no input files
compilation terminated.
make[1]: *** [/opt/devkitpro/devkitARM/base_rules:95: videotest.o] Error 1
make: *** [Makefile:110: build] Error 2
```

When googling it I end up at issue #7 of this test suite. Do you have any idea why this could be happening? If not, would you be kind enough to provide a binary of the latest version (I am still using an older one I found on a forum).

**Comment by endrift** [comment]
Looks like the behavior of grit changed at some point without warning...that's annoying. I'll have a fix for this soon.

**Comment by jsmolka** [comment]
Thank you!
