### ISSUE TITLE
Shifter edge cases

### ISSUE THREAD

**Issue by ltukezl** [mgba-emu/suite#16]
https://github.com/mgba-emu/suite/blob/master/src/shifter.c#L107

Why does this end up being 0x80000FFF and not 0?
As per gbatek:
- Zero Shift Amount (Shift Register by Immediate, with Immediate=0)
-- ASR#0: Interpreted as ASR#32, ie. Op2 and C are filled by Bit 31 of Rm.
and arm7tdmi documentation
- The form of the shift ﬁeld which might be expected to give ASR #0 is used to encode
ASR #32.

Maybe test case for lsl , lsr, asr could be implemented?

**Comment by endrift** [comment]
Bit 31 of Rm here is 1, not 0, so that would imply it'd be 0xFFFFFFFF, not 0. That said, I'd need to double check what's actually going on.

**Comment by endrift** [comment]
Looks like it assembles out the ASR in that instruction, so the test is broken. Will fix it when I can test on hardware tomorrow. Good catch.
