### ISSUE TITLE
Both tests fail to start on My Boy! Free (android emulator)

### ISSUE THREAD

**Issue by sqrg** [mgba-emu/suite#3]
**Android**: v5.0.2
**Emulator**: My Boy! Free
**Suit version**: v0-r19
**Issue**: After pressing A on either test, it briefly shows 'Testing...' and then it goes back to the menu.

**Comment by endrift** [comment]
Sounds like a bug in My Boy! to me, since the suite works on hardware and every other emulator I've thrown it at. Try reporting it to the My Boy! devs.

**Comment by sqrg** [comment]
Yes, you are correct.

I shouldn't have reported this as an issue with the test without thinking a little. Sorry.
