### ISSUE TITLE
Error when compiling on Mac OS X High Sierra

### ISSUE THREAD

**Issue by PikalaxALT** [mgba-emu/suite#7]
Using devkitARM v47, with environment variables defined as described by devkitPro team
Using GNU Make 3.81 for i386-apple-darwin11.3.0 (also happens with GNU Make 4.2.1 for x86_64-apple-darwin17.0.0)

The following console output has been edited to mask my identity.

    $ make
    grit -ff ${HOME}/gba-test/gfx/degenerateObjTransform.grit -fts -odegenerateObjTransform
    degenerateObjTransform.s
    arm-none-eabi-gcc -MMD -MP -MF ${HOME}/gba-test/build/degenerateObjTransform.d -x assembler-with-cpp -mthumb -mthumb-interwork -march=armv4t -mcpu=arm7tdmi -mtune=arm7tdmi -I${HOME}/gba-test/include -I${HOME}/devkitPro/libgba/include -I${HOME}/gba-test/build -c degenerateObjTransform.s -o degenerateObjTransform.o 
    grit -ff ${HOME}/gba-test/gfx/font.grit -fts -ofont
    font.s
    arm-none-eabi-gcc -MMD -MP -MF ${HOME}/gba-test/build/font.d -x assembler-with-cpp -mthumb -mthumb-interwork -march=armv4t -mcpu=arm7tdmi -mtune=arm7tdmi -I${HOME}/gba-test/include -I${HOME}/devkitPro/libgba/include -I${HOME}/gba-test/build -c font.s -o font.o 
    grit -ff ${HOME}/gba-test/gfx/videotest.grit -fts -ovideotest
    videotest.s
    arm-none-eabi-gcc -MMD -MP -MF ${HOME}/gba-test/build/videotest.d -x assembler-with-cpp -mthumb -mthumb-interwork -march=armv4t -mcpu=arm7tdmi -mtune=arm7tdmi -I${HOME}/gba-test/include -I${HOME}/devkitPro/libgba/include -I${HOME}/gba-test/build -c videotest.s -o videotest.o 
    arm-none-eabi-gcc: error: videotest.s: No such file or directory
    arm-none-eabi-gcc: warning: '-x assembler-with-cpp' after last input file has no effect
    arm-none-eabi-gcc: fatal error: no input files
    compilation terminated.
    make[1]: *** [videotest.o] Error 1
    rm font.s degenerateObjTransform.s
    make: *** [build] Error 2

**Comment by endrift** [comment]
Is this still a problem? It looks like your working tree wasn't clean.

**Comment by endrift** [comment]
Closing due to lack of reply.
